---
version: 3

tasks:
  start:dev:
    aliases: [start]
    cmd: hugo server --bind 0.0.0.0 --buildDrafts --buildExpired --buildFuture
  start:prod: hugo server --bind 0.0.0.0
  build: hugo build
  upgrade:
    cmds:
      - git pull
      - task: build
